<?php
/**
 * Created by Solaiman Kmail <psokmail@gmail.com>
 */

namespace Tests\Fixtures\Classes\Cases;


class Firm extends \App\Sync\Cases\Firm
{
    public function questions(): array
    {
        return parent::questions(); // TODO: Change the autogenerated stub
    }
}